version: '3.8'

services:
  api_zeus:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8008 --reload
    volumes:
      - .:/usr/src/app
    ports:
      - 8008:8008
     
    environment:
      - USER=sa
      - PASSWORD=i3kygbb2
      - SERVER=10.102.1.3
      - PORT=1433
      - DATABASE=sifinca
      - DRIVER=freeTDS
 