version: '3.8'

services:
  api_zeus:
    #image: us.gcr.io/sifinca-1329/api_zeus:latest
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8008 --reload
    volumes:
      - .:/usr/src/app
    ports:
      - 8008:8008
     
    environment:
      - USER=sainventario
      - PASSWORD=z
<<<<<<< HEAD
      - SERVER= 192.168.8.130
=======
      - SERVER=localhost
>>>>>>> ed6899c56c9addb013045db4f7e68e1bb9400405
      - PORT=51433
      - DATABASE=Contabilidad_Ladrillera
      - DRIVER=freeTDS
 