version: '3.8'

services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8008 --reload
    volumes:
      - .:/usr/src/app
    ports:
      - 8089:8008
      - 5679:5678
    env_file: .env 
    environment:
      - USER=sainventario
      - PASSWORD=z
      - SERVER=localhost #192.168.0.9
      - PORT=51433
      - DATABASE=Contabilidad_Ladrillera
      - DRIVER=freeTDS
      - DB_INVENTARIO=Inventario_Ladrillera
      - DB_NOMINA=Nomina
      - DB_CONTABILIDAD=Contabilidad_Ladrillera
 